name: Generate and Release VHDL93 Docset

on:
  push:
    tags:
      - "v*"  # Trigger when a new tag like v1.0 is pushed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: pip install -r requirements.txt  # install dependencies

      - name: Generate Docset
        run: python website2docset.py -n VHDL93  -i icon.png HDL-Docs\  # script to generate docset

      - name: Archive Docset
        run: zip -r VHDL93.zip VHDL93.docset

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: VHDL93.zip
          token: ${{ secrets.VHDL_TOKEN }}

